### ISSUE TITLE
`ACT.Google.DM.NCR.user.js` and `ACT.Google.DM.Trackless.user.js` bug

### ISSUE THREAD

**Issue by LaureatePoet** [ACTCD/Userscripts#1]
I installed scripts through `https://greasyfork.org/zh-CN/users/885672-actcd`.
----
about `ACT.Google.DM.NCR.user.js` :

My device default language is English , Chrome is same to.
When I use Google under `ACT.Google.DM.NCR.user.js`, the script options both are `EN`, `US`.
![image](https://user-images.githubusercontent.com/42093310/165880986-c646c680-4483-4c5d-8687-e90a5f630470.png)

----
about `ACT.Google.DM.Trackless.user.js`

access Google map: `https://www.google.com/maps/***` when `ACT.Google.DM.Trackless.user.js` is enable, I can't be able to move the page through the mouse, But the mouse wheel can enlarge and reduce the map.

**Comment by ACTCD** [comment]
Q1: This is expected, `NCR (No country redirect)` is to stay in the default `en_US` region/language service, the `button` is to assist you to quickly switch between `browser preferred language` and `en_US`. This problem has been optimized, please update the script. Now no longer insert the button when the setting is same, and you will only get the NCR feature.

Q2: It has been fixed, please update the script.
