### ISSUE TITLE
Google.DM.NCR bug

### ISSUE THREAD

**Issue by Meonthb** [ACTCD/Userscripts#2]
当系统语言设置为英文时，两个选项都是英语。。。无法选择中文/中国地区
![](https://i.imgur.com/rXSzIJs.jpg)

**Comment by LaureatePoet** [comment]
![image](https://user-images.githubusercontent.com/42093310/168271323-d140a131-c6ff-4b3e-b0e2-8eccac0437ca.png)
me too.

**Comment by ACTCD** [comment]
@LaureatePoet Unlike the previous modification, the toggle button is now displayed anyway, and if your preferred language is the same as `en-US`, it now displays as a non-clickable single button to indicate your current language setting, at the same time you can stiil switch regions.
By the way, `N/A` means that you switch to a language other than your preferred language and your second language or you have not set a language, and clicking the button will switch to your preferred language.
