### ISSUE TITLE
[Bug Report] ACT.YouTube.DM.PiP - PiP may not be turned off.

### ISSUE THREAD

**Issue by SunBK201** [ACTCD/Userscripts#6]
存在一定的概率在开启 PiP 后，再次点击 PiP 按钮无法关闭 PiP，表现为 PiP 窗口已经关闭，但是主视频播放窗口仍然提示正在进行 PiP 模式播放。要解决该问题需要手动暂停视频再点击播放才得以回正，发现进行一次手动回正后该问题消失，但是重新 reload 页面后该问题又复现。

OS: macOS 13 Ventura
Browser: Safari
Safari extension: Userscript

**Comment by ACTCD** [comment]
是否使用最新版本脚本？我这边无法复现。您能否查看一下浏览器控制台，是否有任何错误输出？

**Comment by SunBK201** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/49178170/199986633-8473c203-592a-4f62-bc47-5d6f2e572889.png">
版本使用的是最新版本 20220722.1

**Comment by SunBK201** [comment]
https://user-images.githubusercontent.com/49178170/199989199-82d90826-adbd-46ff-a9a6-29a447634692.mp4

**Comment by ACTCD** [comment]
没有有价值的信息，无法复现意味着我能做的很有限，没有方向调试和解决问题。

我看到您同时在使用其它脚本，您能否尝试仅加载此脚本，看看是否依然有问题？

我记得好像曾经有类似问题，已经通过增加适配 Safari 独有 API 得到改善和解决。

**Comment by SunBK201** [comment]
https://user-images.githubusercontent.com/49178170/200104763-2b012304-b904-46bc-a45d-2b02dd2ad27d.mp4

已确认其他脚本对 ACT.YouTube.DM.PiP 没有影响，同时发现 iOS Safari 也有相同的问题

**Comment by ACTCD** [comment]
感谢您的跟踪调试。

请您关闭此脚本，直接在控制台尝试以下代码，看是否仍然能复现问题：
```js
function pip() {
    const video = document.querySelector('video[src]');
    console.log(video, video.webkitPresentationMode);
    if (video.webkitPresentationMode != 'inline') {
        video.webkitSetPresentationMode('inline');
    } else {
        video.webkitSetPresentationMode('picture-in-picture');
    }
}
```

在控制台执行以上代码后，尝试手动反复调用 `pip();` 来切换画中画状态。

**Comment by SunBK201** [comment]
https://user-images.githubusercontent.com/49178170/200113972-6fa56ea0-34d0-4a15-98fb-7031d221761f.mp4


如视频所见，在没有点击一次暂停视频之前，`pip()` 是不生效的。

**Comment by ACTCD** [comment]
OK，我刚刚复现出你的问题了。

需要在保持画中画模式的时候切换到一个新的视频，就可以稳定复现此问题。

**Comment by SunBK201** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/49178170/200121189-07f8a34c-a440-4196-ac86-6ec650eb8168.png">
可以确定暂停前后选择器选择了同一个 `video` 元素，区别在于触发暂停后的 `video` 具有子节点 (video 的用户代理)，暂停前没有。

**Comment by ACTCD** [comment]
更有可能是 Youtube 的 AJAX 和画中画适配导致的问题。我会尝试看有没有变通方式解决。

**Comment by SunBK201** [comment]
应该是 Youtube 的问题，我尝试在其他网站手动开启 PiP 没有此类问题。

**Comment by ACTCD** [comment]
您应该注意我上面提到的触发条件，必须是在开启画中画的情况下进入一个新视频。

也就是说新视频必须是通过 AJAX 加载，并在同一个 `video` 元素中播放，其他网站不一定能满足这个条件。

另外我已经找到一种变通方式解决，稍后更新脚本。感谢您的反馈！

**Comment by ACTCD** [comment]
已经推送更新。

请更新脚本后看看是否解决，如果问题解决，请关闭这个 issue 吧:)

**Comment by SunBK201** [comment]
问题已修复！Thanks！
